=== verejohns/docyt/app/assets/schemas/report-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Report",
  "description": "A standard report",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique textual ID of the template"
    },
    "name": {
      "type": "string",
      "description": "User-facing name of the template"
    },
    "rank": {
      "type": "integer",
      "default": 0,
      "description": "Defines template's position in the list of templates. The lower the rank, the higher the position will be in the list."
    },
    "standard_category_ids": {
      "type": "array",
      "description": "A list of standard industries where this template will be shown",
      "items": [
        {
          "type": "integer"
        }
      ]
    },
    "draft": {
      "type": "boolean",
      "description": "When true, template won't be visible in the UI",
      "default": false
    },
    "period_type": {
      "type": "string",
      "description": "Type of report - daily or monthly",
      "enum": [
        "daily",
        "monthly"
      ],
      "default": "monthly"
    },
    "missing_transactions_calculation_disabled": {
      "type": "boolean",
      "description": "Tells if template requires to calculate missing Ledger transactions",
      "default": true
    },
    "factory_class": {
      "type": "string",
      "description": "This field represents which report factory class is used for this report",
      "default": "ReportFactory"
    },
    "enabled_budget_compare": {
      "type": "boolean",
      "description": "Does this report report compare feature?",
      "default": true
    },
    "enabled_blank_value_for_metric": {
      "type": "boolean",
      "description": "Can the value of item_value be nil for the metric of this report?",
      "default": false
    },
    "total_column_visible": {
      "type": "boolean",
      "description": "Hide or show total column?",
      "default": true
    },
    "multi_entity_columns": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "description": "Type of the column",
            "enum": [
              "actual",
              "percentage",
              "gross_actual",
              "gross_percentage"
            ]
          },
          "name": {
            "type": "string",
            "description": "Column name"
          }
        },
        "required": [
          "type",
          "name"
        ],
        "additionalProperties": false
      }
    },
    "view_by_options": {
      "type": "array",
      "description": "A list of metric codes that will be used to slice the data by in the UI. Every metric in the list will be presented as a checkbox.",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "depends_on": {
      "type": "array",
      "description": "A list of reports on which this report depend upon",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "accounting_class_check_disabled": {
      "type": "boolean",
      "description": "Tells if template calculate values without checking accounting department",
      "default": false
    },
    "edit_mapping_disabled": {
      "type": "boolean",
      "description": "Tell if user can edit mapping",
      "default": false
    },
    "columns": {
      "type": "array",
      "description": "Columns that will be shown in this report",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "description": "Column type",
            "enum": [
              "actual",
              "percentage",
              "budget_actual",
              "budget_percentage",
              "budget_variance",
              "variance",
              "variance_percentage",
              "gross_percentage",
              "gross_actual"
            ]
          },
          "range": {
            "type": "string",
            "description": "Date range that this column is covering",
            "enum": [
              "current_period",
              "ytd",
              "mtd"
            ]
          },
          "year": {
            "type": "string",
            "description": "Year that is covered by this column",
            "enum": [
              "current",
              "prior",
              "previous_period"
            ]
          },
          "name": {
            "type": "string",
            "description": "Column name"
          }
        },
        "required": [
          "type",
          "range",
          "name"
        ],
        "additionalProperties": false
      }
    },
    "items": {
      "type": "array",
      "description": "List of report rows",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Unique textual identifier of this row"
          },
          "parent_id": {
            "type": "string",
            "description": "A reference to the parent row (when the row is nested)"
          },
          "name": {
            "type": "string",
            "description": "User-facing name of the row"
          },
          "totals": {
            "type": "boolean",
            "description": "Calculate totals for this section?",
            "default": false
          },
          "show": {
            "type": "boolean",
            "description": "Show total row?",
            "default": true
          },
          "negative_for_total": {
            "type": "boolean",
            "description": "This field is used when calculate total value of parent item with negative number",
            "default": false
          },
          "negative": {
            "type": "boolean",
            "description": "This field represents that this item's actual value will be multipled with -1",
            "default": false
          },
          "balance_sheet": {
            "type": "boolean",
            "description": "Use balance sheet ledger for calculation?",
            "default": false
          },
          "depth_diff": {
            "type": "integer",
            "description": "This field is used for displaying the item in report table from front-end"
          },
          "_description": {
            "type": "string",
            "description": "User-facing description of the row"
          },
          "account_type": {
            "type": "string",
            "description": "This field indicates chart of account type for balance sheet report's leaf item"
          },
          "type": {
            "type": "object",
            "description": "Defines how the row is calculated",
            "properties": {
              "name": {
                "type": "string",
                "description": "Type of the row",
                "enum": [
                  "quickbooks_ledger",
                  "metric",
                  "reference",
                  "stats"
                ]
              },
              "reference": {
                "type": "string",
                "description": "(used for type = reference) A reference to row ID from another report"
              },
              "src_column_range": {
                "type": "string",
                "description": "???"
              },
              "calculation_type": {
                "type": "string",
                "description": "Type of calculation to use in Quickbooks",
                "enum": [
                  "bs_net_change",
                  "bs_prior_day",
                  "general_ledger",
                  "bs_balance",
                  "bank_general_ledger",
                  "tax_collected_value",
                  "debits_only",
                  "credits_only"
                ],
                "default": "general_ledger"
              },
              "exclude_ledgers": {
                "type": "string",
                "description": "Ledgers to exclude from common ledger for tax calculation type",
                "enum": [
                  "bank",
                  "bank_and_accounts_payable"
                ],
                "default": "general_ledger"
              },
              "use_mapping": {
                "type": "object",
                "description": "A property that enables this row to re-use mapping from another row",
                "properties": {
                  "item_id": {
                    "type": "string",
                    "description": "ID of the row from which the mapping will be used in this row"
                  }
                }
              },
              "metric": {
                "type": "object"
              },
              "default_accounts": {
                "type": "array",
                "description": "List of chart of accounts that will be loaded by default into mapping",
                "items": {
                  "type": "object",
                  "properties": {
                    "account_type": {
                      "type": "string"
                    },
                    "account_detail_type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "account_type",
                    "account_detail_type"
                  ],
                  "additionalProperties": false
                }
              }
            },
            "required": [
              "name"
            ],
            "additionalProperties": false
          },
          "values": {
            "type": "object",
            "description": "Formulae that is used to calculate the value for this row",
            "properties": {
              "actual": {
                "type": "object",
                "description": "How to calculate values for actual column",
                "properties": {
                  "value": {
                    "type": "object"
                  }
                }
              },
              "percentage": {
                "type": "object",
                "description": "How to calculate values for percentage column",
                "properties": {
                  "value": {
                    "type": "object"
                  }
                }
              },
              "variance_percentage": {
                "type": "object",
                "description": "How to calculate values for variance percentage column",
                "properties": {
                  "value": {
                    "type": "object"
                  }
                }
              },
              "gross_actual": {
                "type": "object",
                "description": "How to calculate values for gross actual column",
                "properties": {
                  "value": {
                    "type": "object"
                  }
                }
              },
              "gross_percentage": {
                "type": "object",
                "description": "How to calculate values for gross percentage column",
                "properties": {
                  "value": {
                    "type": "object"
                  }
                }
              }
            },
            "additionalProperties": false
          }
        },
        "required": [
          "id",
          "name"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "id",
    "name",
    "columns",
    "items"
  ],
  "additionalProperties": false
}

=== verejohns/docyt/app/assets/jsons/templates/profit_and_loss.json
{
  "id": "profit_and_loss",
  "name": "Profit and Loss",
  "factory_class": "ProfitAndLossReportFactory",

  "columns": [
    {"type": "actual", "range": "current_period", "year": "current", "name": "PTD $"},
    {"type": "percentage", "range": "current_period", "year": "current", "name": "PTD %"},
    {"type": "actual", "range": "current_period", "year": "prior", "name": "PTD LY $"},
    {"type": "percentage", "range": "current_period", "year": "prior", "name": "PTD LY %"},
    {"type": "variance", "range": "current_period", "name": "PTD Var"},
    {"type": "actual", "range": "ytd", "year": "current", "name": "YTD $"},
    {"type": "percentage", "range": "ytd", "year": "current", "name": "YTD %"},
    {"type": "actual", "range": "ytd", "year": "prior", "name": "YTD LY $"},
    {"type": "percentage", "range": "ytd", "year": "prior", "name": "YTD LY %"},
    {"type": "variance", "range": "ytd", "name": "YTD Var"}
  ],
  "accounting_class_check_disabled": true,
  "items": [
    {
      "id": "income",
      "name": "Income",
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "income"
              },
              "arg2": {
                "item_id": "total_income"
              }
            }
          }
        }
      }
    },
    {
      "id": "total_income",
      "name": "Total Income",
      "parent_id": "income",
      "totals": true,
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "total_income"
              },
              "arg2": {
                "item_id": "total_income"
              }
            }
          }
        }
      }
    },
    {
      "id": "cost_of_goods_sold",
      "name": "Cost of Goods Sold",
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "cost_of_goods_sold"
              },
              "arg2": {
                "item_id": "total_cost_of_goods_sold"
              }
            }
          }
        }
      }
    },
    {
      "id": "total_cost_of_goods_sold",
      "name": "Total Cost of Goods Sold",
      "parent_id": "cost_of_goods_sold",
      "totals": true,
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "total_cost_of_goods_sold"
              },
              "arg2": {
                "item_id": "total_cost_of_goods_sold"
              }
            }
          }
        }
      }
    },
    {
      "id": "gross_profit",
      "name": "Gross profit",
      "type": {
        "name": "stats"
      },
      "values": {
        "actual": {
          "value": {
            "expression": {
              "operator": "-",
              "arg1": {
                "item_id": "total_income"
              },
              "arg2": {
                "item_id": "total_cost_of_goods_sold"
              }
            }
          }
        },
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "gross_profit"
              },
              "arg2": {
                "item_id": "total_income"
              }
            }
          }
        }
      }
    },
    {
      "id": "expenses",
      "name": "Expenses",
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "expenses"
              },
              "arg2": {
                "item_id": "total_income"
              }
            }
          }
        }
      }
    },
    {
      "id": "total_expenses",
      "name": "Total Expenses",
      "parent_id": "expenses",
      "totals": true,
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "total_expenses"
              },
              "arg2": {
                "item_id": "total_income"
              }
            }
          }
        }
      }
    },
    {
      "id": "net_operating_income",
      "name": "Net Operating Income",
      "type": {
        "name": "stats"
      },
      "values": {
        "actual": {
          "value": {
            "expression": {
              "operator": "-",
              "arg1": {
                "item_id": "gross_profit"
              },
              "arg2": {
                "item_id": "total_expenses"
              }
            }
          }
        },
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "net_operating_income"
              },
              "arg2": {
                "item_id": "total_income"
              }
            }
          }
        }
      }
    },
    {
      "id": "other_income",
      "name": "Other Income",
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "other_income"
              },
              "arg2": {
                "item_id": "total_income"
              }
            }
          }
        }
      }      
    },
    {
      "id": "total_other_income",
      "name": "Total Other Income",
      "parent_id": "other_income",
      "totals": true,
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "total_other_income"
              },
              "arg2": {
                "item_id": "total_income"
              }
            }
          }
        }
      }
    },
    {
      "id": "other_expenses",
      "name": "Other Expenses",
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "other_expenses"
              },
              "arg2": {
                "item_id": "total_income"
              }
            }
          }
        }
      }
    },
    {
      "id": "total_other_expenses",
      "name": "Total Other Expenses",
      "parent_id": "other_expenses",
      "totals": true,
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "total_other_expenses"
              },
              "arg2": {
                "item_id": "total_income"
              }
            }
          }
        }
      }
    },
    {
      "id": "net_other_income",
      "name": "Net Other Income",
      "type": {
        "name": "stats"
      },
      "values": {
        "actual": {
          "value": {
            "expression": {
              "operator": "-",
              "arg1": {
                "item_id": "total_other_income"
              },
              "arg2": {
                "item_id": "total_other_expenses"
              }
            }
          }
        },
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "net_other_income"
              },
              "arg2": {
                "item_id": "total_income"
              }
            }
          }
        }
      }
    },
    {
      "id": "net_profit",
      "name": "Net Profit",
      "type": {
        "name": "stats"
      },
      "values": {
        "actual": {
          "value": {
            "expression": {
              "operator": "+",
              "arg1": {
                "item_id": "net_operating_income"
              },
              "arg2": {
                "item_id": "net_other_income"
              }
            }
          }
        },
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "net_profit"
              },
              "arg2": {
                "item_id": "total_income"
              }
            }
          }
        }
      }
    }
  ]
}

=== verejohns/docyt/app/assets/jsons/templates/schedule_9.json
{
  "id": "schedule_9",
  "name": "Schedule 9 - Utilities",
  "depends_on": [
    "owners_operating_statement"
  ],
  "rank": 11,
  "standard_category_ids": [9],
  "draft": false,

  "columns": [
    {"type": "actual", "range": "current_period", "year": "current", "name": "PTD $"},
    {"type": "percentage", "range": "current_period", "year": "current", "name": "PTD %"},
    {"type": "budget_actual", "range": "current_period", "year": "current", "name": "Budget $"},
    {"type": "budget_percentage", "range": "current_period", "year": "current", "name": "Budget %"},
    {"type": "budget_variance", "range": "current_period", "name": "Budget Var"},
    {"type": "actual", "range": "current_period", "year": "prior", "name": "PTD LY $"},
    {"type": "percentage", "range": "current_period", "year": "prior", "name": "PTD LY %"},
    {"type": "actual", "range": "ytd", "year": "current", "name": "YTD $"},
    {"type": "percentage", "range": "ytd", "year": "current", "name": "YTD %"},
    {"type": "budget_actual", "range": "ytd", "year": "current", "name": "Budget $"},
    {"type": "budget_percentage", "range": "ytd", "year": "current", "name": "Budget %"},
    {"type": "budget_variance", "range": "ytd", "name": "Budget Var"},
    {"type": "actual", "range": "ytd", "year": "prior", "name": "YTD LY $"},
    {"type": "percentage", "range": "ytd", "year": "prior", "name": "YTD LY %"}
  ],
  "missing_transactions_calculation_disabled": false,
  "view_by_options": ["rooms_sold"],
  "items": [
    {
      "id": "summary",
      "name": "Summary",
      "_description": "This section consists of items that use standard hotel metrics to calculate the values"
    },
    {
      "id": "rooms_available",
      "name": "Rooms Available to sell",
      "parent_id": "summary",
      "type": {
        "name": "reference",
        "reference": "owners_operating_statement/rooms_available",
        "metric": {
          "name": "Available Rooms"
        }
      }
    },
    {
      "id": "rooms_sold",
      "name": "Rooms Sold",
      "parent_id": "summary",
      "type": {
        "name": "reference",
        "reference": "owners_operating_statement/rooms_sold",
        "metric": {
          "name": "Sold Rooms"
        }
      }
    },
    {
      "id": "occupancy_percent",
      "name": "Occupancy %",
      "parent_id": "summary",
      "type": {
        "name": "reference",
        "reference": "owners_operating_statement/occupancy_percent"
      },
      "values": {
        "actual": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "rooms_sold"
              },
              "arg2": {
                "item_id": "rooms_available"
              }
            }
          }
        }
      }
    },
    {
      "id": "utilities",
      "name": "Utilities"
    },
    {
      "id": "electricity",
      "name": "Electricity",
      "parent_id": "utilities",
      "type": {
        "name": "quickbooks_ledger"
      },
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "electricity"
              },
              "arg2": {
                "item_id": "owners_operating_statement/total_operating_revenue"
              }
            }
          }
        }
      }
    },
    {
      "id": "gas",
      "name": "Gas",
      "parent_id": "utilities",
      "type": {
        "name": "quickbooks_ledger"
      },
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "gas"
              },
              "arg2": {
                "item_id": "owners_operating_statement/total_operating_revenue"
              }
            }
          }
        }
      }
    },
    {
      "id": "oil",
      "name": "Oil",
      "parent_id": "utilities",
      "type": {
        "name": "quickbooks_ledger"
      },
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "oil"
              },
              "arg2": {
                "item_id": "owners_operating_statement/total_operating_revenue"
              }
            }
          }
        }
      }
    },
    {
      "id": "water_sewer",
      "name": "Water/Sewer",
      "parent_id": "utilities",
      "type": {
        "name": "quickbooks_ledger"
      },
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "water_sewer"
              },
              "arg2": {
                "item_id": "owners_operating_statement/total_operating_revenue"
              }
            }
          }
        }
      }
    },
    {
      "id": "steam",
      "name": "Steam",
      "parent_id": "utilities",
      "type": {
        "name": "quickbooks_ledger"
      },
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "steam"
              },
              "arg2": {
                "item_id": "owners_operating_statement/total_operating_revenue"
              }
            }
          }
        }
      }
    },
    {
      "id": "chilled_water",
      "name": "Chilled Water",
      "parent_id": "utilities",
      "type": {
        "name": "quickbooks_ledger"
      },
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "chilled_water"
              },
              "arg2": {
                "item_id": "owners_operating_statement/total_operating_revenue"
              }
            }
          }
        }
      }
    },
    {
      "id": "other_fuels",
      "name": "Other Fuels",
      "parent_id": "utilities",
      "type": {
        "name": "quickbooks_ledger"
      },
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "other_fuels"
              },
              "arg2": {
                "item_id": "owners_operating_statement/total_operating_revenue"
              }
            }
          }
        }
      }
    },
    {
      "id": "contract_services",
      "name": "Contract Services",
      "parent_id": "utilities",
      "type": {
        "name": "quickbooks_ledger"
      },
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "contract_services"
              },
              "arg2": {
                "item_id": "owners_operating_statement/total_operating_revenue"
              }
            }
          }
        }
      }
    },
    {
      "id": "total_utilities",
      "name": "Total Utilities",
      "parent_id": "utilities",
      "totals": true,
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "total_utilities"
              },
              "arg2": {
                "item_id": "owners_operating_statement/total_operating_revenue"
              }
            }
          }
        }
      }
    }
  ]
}

=== verejohns/docyt/app/assets/jsons/templates/vendor_report.json
{
  "id": "vendor_report",
  "name": "Vendor Report",
  "factory_class": "VendorReportFactory",

  "rank": 20,
  "draft": false,
  "enabled_budget_compare": false,
  "total_column_visible": false,
  "accounting_class_check_disabled": true,
  "standard_category_ids": [8, 9],
  "edit_mapping_disabled": true,
  "columns": [
    {
      "type": "actual",
      "range": "current_period",
      "year": "current",
      "name": "PTD $"
    },
    {
      "type": "percentage",
      "range": "current_period",
      "year": "current",
      "name": "PTD %"
    },
    {
      "type": "actual",
      "range": "current_period",
      "year": "prior",
      "name": "PTD LY $"
    },
    {
      "type": "percentage",
      "range": "current_period",
      "year": "prior",
      "name": "PTD LY %"
    },
    { "type": "variance", "range": "current_period", "name": "Variance" },
    {
      "type": "actual",
      "range": "ytd",
      "year": "current",
      "name": "YTD $"
    },
    {
      "type": "percentage",
      "range": "ytd",
      "year": "current",
      "name": "YTD %"
    },
    {
      "type": "actual",
      "range": "ytd",
      "year": "prior",
      "name": "YTD LY $"
    },
    {
      "type": "percentage",
      "range": "ytd",
      "year": "prior",
      "name": "YTD LY %"
    },
    { "type": "variance", "range": "ytd", "name": "Variance" }
  ],
  "items": []
}
