=== verejohns/docyt/app/assets/schemas/report-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Report",
  "description": "A standard report",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique textual ID of the template"
    },
    "name": {
      "type": "string",
      "description": "User-facing name of the template"
    },
    "rank": {
      "type": "integer",
      "default": 0,
      "description": "Defines template's position in the list of templates. The lower the rank, the higher the position will be in the list."
    },
    "standard_category_ids": {
      "type": "array",
      "description": "A list of standard industries where this template will be shown",
      "items": [
        {
          "type": "integer"
        }
      ]
    },
    "draft": {
      "type": "boolean",
      "description": "When true, template won't be visible in the UI",
      "default": false
    },
    "period_type": {
      "type": "string",
      "description": "Type of report - daily or monthly",
      "enum": [
        "daily",
        "monthly"
      ],
      "default": "monthly"
    },
    "missing_transactions_calculation_disabled": {
      "type": "boolean",
      "description": "Tells if template requires to calculate missing Ledger transactions",
      "default": true
    },
    "factory_class": {
      "type": "string",
      "description": "This field represents which report factory class is used for this report",
      "default": "ReportFactory"
    },
    "enabled_budget_compare": {
      "type": "boolean",
      "description": "Does this report report compare feature?",
      "default": true
    },
    "enabled_blank_value_for_metric": {
      "type": "boolean",
      "description": "Can the value of item_value be nil for the metric of this report?",
      "default": false
    },
    "total_column_visible": {
      "type": "boolean",
      "description": "Hide or show total column?",
      "default": true
    },
    "multi_entity_columns": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "description": "Type of the column",
            "enum": [
              "actual",
              "percentage",
              "gross_actual",
              "gross_percentage"
            ]
          },
          "name": {
            "type": "string",
            "description": "Column name"
          }
        },
        "required": [
          "type",
          "name"
        ],
        "additionalProperties": false
      }
    },
    "view_by_options": {
      "type": "array",
      "description": "A list of metric codes that will be used to slice the data by in the UI. Every metric in the list will be presented as a checkbox.",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "depends_on": {
      "type": "array",
      "description": "A list of reports on which this report depend upon",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "accounting_class_check_disabled": {
      "type": "boolean",
      "description": "Tells if template calculate values without checking accounting department",
      "default": false
    },
    "edit_mapping_disabled": {
      "type": "boolean",
      "description": "Tell if user can edit mapping",
      "default": false
    },
    "columns": {
      "type": "array",
      "description": "Columns that will be shown in this report",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "description": "Column type",
            "enum": [
              "actual",
              "percentage",
              "budget_actual",
              "budget_percentage",
              "budget_variance",
              "variance",
              "variance_percentage",
              "gross_percentage",
              "gross_actual"
            ]
          },
          "range": {
            "type": "string",
            "description": "Date range that this column is covering",
            "enum": [
              "current_period",
              "ytd",
              "mtd"
            ]
          },
          "year": {
            "type": "string",
            "description": "Year that is covered by this column",
            "enum": [
              "current",
              "prior",
              "previous_period"
            ]
          },
          "name": {
            "type": "string",
            "description": "Column name"
          }
        },
        "required": [
          "type",
          "range",
          "name"
        ],
        "additionalProperties": false
      }
    },
    "items": {
      "type": "array",
      "description": "List of report rows",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Unique textual identifier of this row"
          },
          "parent_id": {
            "type": "string",
            "description": "A reference to the parent row (when the row is nested)"
          },
          "name": {
            "type": "string",
            "description": "User-facing name of the row"
          },
          "totals": {
            "type": "boolean",
            "description": "Calculate totals for this section?",
            "default": false
          },
          "show": {
            "type": "boolean",
            "description": "Show total row?",
            "default": true
          },
          "negative_for_total": {
            "type": "boolean",
            "description": "This field is used when calculate total value of parent item with negative number",
            "default": false
          },
          "negative": {
            "type": "boolean",
            "description": "This field represents that this item's actual value will be multipled with -1",
            "default": false
          },
          "balance_sheet": {
            "type": "boolean",
            "description": "Use balance sheet ledger for calculation?",
            "default": false
          },
          "depth_diff": {
            "type": "integer",
            "description": "This field is used for displaying the item in report table from front-end"
          },
          "_description": {
            "type": "string",
            "description": "User-facing description of the row"
          },
          "account_type": {
            "type": "string",
            "description": "This field indicates chart of account type for balance sheet report's leaf item"
          },
          "type": {
            "type": "object",
            "description": "Defines how the row is calculated",
            "properties": {
              "name": {
                "type": "string",
                "description": "Type of the row",
                "enum": [
                  "quickbooks_ledger",
                  "metric",
                  "reference",
                  "stats"
                ]
              },
              "reference": {
                "type": "string",
                "description": "(used for type = reference) A reference to row ID from another report"
              },
              "src_column_range": {
                "type": "string",
                "description": "???"
              },
              "calculation_type": {
                "type": "string",
                "description": "Type of calculation to use in Quickbooks",
                "enum": [
                  "bs_net_change",
                  "bs_prior_day",
                  "general_ledger",
                  "bs_balance",
                  "bank_general_ledger",
                  "tax_collected_value",
                  "debits_only",
                  "credits_only"
                ],
                "default": "general_ledger"
              },
              "exclude_ledgers": {
                "type": "string",
                "description": "Ledgers to exclude from common ledger for tax calculation type",
                "enum": [
                  "bank",
                  "bank_and_accounts_payable"
                ],
                "default": "general_ledger"
              },
              "use_mapping": {
                "type": "object",
                "description": "A property that enables this row to re-use mapping from another row",
                "properties": {
                  "item_id": {
                    "type": "string",
                    "description": "ID of the row from which the mapping will be used in this row"
                  }
                }
              },
              "metric": {
                "type": "object"
              },
              "default_accounts": {
                "type": "array",
                "description": "List of chart of accounts that will be loaded by default into mapping",
                "items": {
                  "type": "object",
                  "properties": {
                    "account_type": {
                      "type": "string"
                    },
                    "account_detail_type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "account_type",
                    "account_detail_type"
                  ],
                  "additionalProperties": false
                }
              }
            },
            "required": [
              "name"
            ],
            "additionalProperties": false
          },
          "values": {
            "type": "object",
            "description": "Formulae that is used to calculate the value for this row",
            "properties": {
              "actual": {
                "type": "object",
                "description": "How to calculate values for actual column",
                "properties": {
                  "value": {
                    "type": "object"
                  }
                }
              },
              "percentage": {
                "type": "object",
                "description": "How to calculate values for percentage column",
                "properties": {
                  "value": {
                    "type": "object"
                  }
                }
              },
              "variance_percentage": {
                "type": "object",
                "description": "How to calculate values for variance percentage column",
                "properties": {
                  "value": {
                    "type": "object"
                  }
                }
              },
              "gross_actual": {
                "type": "object",
                "description": "How to calculate values for gross actual column",
                "properties": {
                  "value": {
                    "type": "object"
                  }
                }
              },
              "gross_percentage": {
                "type": "object",
                "description": "How to calculate values for gross percentage column",
                "properties": {
                  "value": {
                    "type": "object"
                  }
                }
              }
            },
            "additionalProperties": false
          }
        },
        "required": [
          "id",
          "name"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "id",
    "name",
    "columns",
    "items"
  ],
  "additionalProperties": false
}

=== verejohns/docyt/spec/fixtures/templates/revenue_report.json
{
  "id": "revenue_report",
  "name": "Daily/Monthly Revenue report",
  "rank": 17,
  "standard_category_ids": [
    9
  ],
  "draft": false,
  "period_type": "daily",
  "columns": [
    {
      "type": "actual",
      "range": "current_period",
      "year": "current",
      "name": "PTD $"
    },
    {
      "type": "budget_actual",
      "range": "current_period",
      "year": "current",
      "name": "Budget $"
    },
    {
      "type": "budget_percentage",
      "range": "current_period",
      "year": "current",
      "name": "Budget %"
    },
    {
      "type": "budget_variance",
      "range": "current_period",
      "name": "Budget Var"
    },
    {
      "type": "actual",
      "range": "current_period",
      "year": "prior",
      "name": "PTD LY $"
    },
    {
      "type": "variance",
      "range": "current_period",
      "name": "PTD Var"
    },
    {
      "type": "actual",
      "range": "mtd",
      "year": "current",
      "name": "MTD"
    },
    {
      "type": "actual",
      "range": "ytd",
      "year": "current",
      "name": "YTD $"
    },
    {
      "type": "budget_actual",
      "range": "ytd",
      "year": "current",
      "name": "Budget $"
    },
    {
      "type": "budget_variance",
      "range": "ytd",
      "name": "Budget Var"
    },
    {
      "type": "actual",
      "range": "ytd",
      "year": "prior",
      "name": "YTD LY $"
    },
    {
      "type": "variance",
      "range": "ytd",
      "name": "YTD Var"
    }
  ],
  "missing_transactions_calculation_disabled": false,
  "view_by_options": [
    "rooms_sold"
  ],
  "items": [
    {
      "id": "metrics",
      "name": "Metrics",
      "_description": "This section consists of items that use standard hotel metrics to calculate the values"
    },
    {
      "id": "rooms_available",
      "name": "Rooms Available to sell",
      "parent_id": "metrics",
      "type": {
        "name": "metric",
        "metric": {
          "name": "Available Rooms",
          "code": "rooms_available"
        }
      }
    },
    {
      "id": "rooms_sold",
      "name": "Rooms Sold",
      "parent_id": "metrics",
      "type": {
        "name": "metric",
        "metric": {
          "name": "Sold Rooms",
          "code": "rooms_sold"
        }
      }
    },
    {
      "id": "occupancy_percent",
      "name": "Occupancy percentage",
      "parent_id": "metrics",
      "type": {
        "name": "stats"
      },
      "values": {
        "actual": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "rooms_sold"
              },
              "arg2": {
                "item_id": "rooms_available"
              }
            }
          }
        }
      }
    },
    {
      "id": "adr",
      "name": "ADR",
      "parent_id": "metrics",
      "type": {
        "name": "stats"
      },
      "values": {
        "actual": {
          "value": {
            "expression": {
              "operator": "/",
              "arg1": {
                "item_id": "rooms_revenue"
              },
              "arg2": {
                "item_id": "rooms_sold"
              }
            }
          }
        }
      }
    },
    {
      "id": "revpar",
      "name": "Revpar",
      "parent_id": "metrics",
      "type": {
        "name": "stats"
      },
      "values": {
        "actual": {
          "value": {
            "expression": {
              "operator": "/",
              "arg1": {
                "item_id": "rooms_revenue"
              },
              "arg2": {
                "item_id": "rooms_available"
              }
            }
          }
        }
      }
    },
    {
      "id": "revenue_department",
      "name": "Revenue by Departments",
      "_description": "This section consists of items that use standard hotel metrics to calculate the values"
    },
    {
      "id": "rooms_revenue",
      "name": "Rooms Revenue",
      "parent_id": "revenue_department",
      "type": {
        "name": "quickbooks_ledger"
      }
    },
    {
      "id": "minor_operated",
      "name": "Minor Operated",
      "parent_id": "revenue_department",
      "type": {
        "name": "quickbooks_ledger"
      }
    },
    {
      "id": "f_b",
      "name": "F&B",
      "parent_id": "revenue_department",
      "type": {
        "name": "quickbooks_ledger"
      }
    },
    {
      "id": "misc",
      "name": "MISC",
      "parent_id": "revenue_department",
      "type": {
        "name": "quickbooks_ledger"
      }
    },
    {
      "id": "total",
      "name": "Total",
      "parent_id": "revenue_department",
      "type": {
        "name": "stats"
      },
      "values": {
        "actual": {
          "value": {
            "expression": {
              "operator": "sum",
              "arg": {
                "sub_items": [
                  {
                    "id": "rooms_revenue",
                    "negative": false
                  },
                  {
                    "id": "minor_operated",
                    "negative": false
                  },
                  {
                    "id": "f_b",
                    "negative": false
                  },
                  {
                    "id": "misc",
                    "negative": false
                  }
                ]
              }
            }
          }
        }
      }
    },
    {
      "id": "tax_collected",
      "name": "Tax Collected",
      "parent_id": "revenue_department",
      "type": {
        "name": "quickbooks_ledger"
      }
    },
    {
      "id": "net",
      "name": "Net",
      "parent_id": "revenue_department",
      "type": {
        "name": "stats"
      },
      "values": {
        "actual": {
          "value": {
            "expression": {
              "operator": "-",
              "arg1": {
                "item_id": "total"
              },
              "arg2": {
                "item_id": "tax_collected"
              }
            }
          }
        }
      }
    },
    {
      "id": "guest_ledger",
      "name": "Guest ledger",
      "balance_sheet": true,
      "_description": "This section consists of items that use standard hotel metrics to calculate the values"
    },
    {
      "id": "guest_begin_period_balance",
      "name": "Beginning of Period Balance",
      "balance_sheet": true,
      "parent_id": "guest_ledger",
      "type": {
        "name": "quickbooks_ledger",
        "calculation_type": "bs_prior_day"
      }
    },
    {
      "id": "guest_net_change",
      "name": "Net Change",
      "balance_sheet": true,
      "parent_id": "guest_ledger",
      "type": {
        "name": "quickbooks_ledger",
        "calculation_type": "bs_balance"
      }
    },
    {
      "id": "guest_end_period_balance",
      "name": "End of Period Balance",
      "balance_sheet": true,
      "parent_id": "guest_ledger",
      "type": {
        "name": "stats"
      },
      "values": {
        "actual": {
          "value": {
            "expression": {
              "operator": "+",
              "arg1": {
                "item_id": "guest_net_change"
              },
              "arg2": {
                "item_id": "guest_begin_period_balance"
              }
            }
          }
        }
      }
    },
    {
      "id": "city_ledger",
      "name": "City ledger",
      "balance_sheet": true,
      "_description": "This section consists of items that use standard hotel metrics to calculate the values"
    },
    {
      "id": "city_begin_period_balance",
      "name": "Beginning of Period Balance",
      "balance_sheet": true,
      "parent_id": "city_ledger",
      "type": {
        "name": "quickbooks_ledger",
        "calculation_type": "bs_prior_day"
      }
    },
    {
      "id": "city_net_change",
      "name": "Net Change",
      "balance_sheet": true,
      "parent_id": "city_ledger",
      "type": {
        "name": "quickbooks_ledger",
        "calculation_type": "bs_balance"
      }
    },
    {
      "id": "city_end_period_balance",
      "name": "End of Period Balance",
      "balance_sheet": true,
      "parent_id": "city_ledger",
      "type": {
        "name": "stats"
      },
      "values": {
        "actual": {
          "value": {
            "expression": {
              "operator": "+",
              "arg1": {
                "item_id": "city_begin_period_balance"
              },
              "arg2": {
                "item_id": "city_net_change"
              }
            }
          }
        }
      }
    },
    {
      "id": "advance_deposit",
      "name": "Advance Deposit",
      "balance_sheet": true,
      "_description": "This section consists of items that use standard hotel metrics to calculate the values"
    },
    {
      "id": "advance_begin_period_balance",
      "name": "Beginning of Period Balance",
      "balance_sheet": true,
      "parent_id": "advance_deposit",
      "type": {
        "name": "quickbooks_ledger",
        "calculation_type": "bs_prior_day"
      }
    },
    {
      "id": "advance_net_change",
      "name": "Net Change",
      "balance_sheet": true,
      "parent_id": "advance_deposit",
      "type": {
        "name": "quickbooks_ledger",
        "calculation_type": "bs_balance"
      }
    },
    {
      "id": "advance_end_period_balance",
      "name": "End of Period Balance",
      "balance_sheet": true,
      "parent_id": "advance_deposit",
      "type": {
        "name": "stats"
      },
      "values": {
        "actual": {
          "value": {
            "expression": {
              "operator": "+",
              "arg1": {
                "item_id": "advance_begin_period_balance"
              },
              "arg2": {
                "item_id": "advance_net_change"
              }
            }
          }
        }
      }
    }
  ]
}

=== verejohns/docyt/app/assets/jsons/templates/schedule_10.json
{
  "id": "schedule_10",
  "name": "Schedule 10 - Management Fees",
  "depends_on": [
    "owners_operating_statement"
  ],
  "rank": 12,
  "standard_category_ids": [9],
  "draft": false,

  "columns": [
    {"type": "actual", "range": "current_period", "year": "current", "name": "PTD $"},
    {"type": "percentage", "range": "current_period", "year": "current", "name": "PTD %"},
    {"type": "budget_actual", "range": "current_period", "year": "current", "name": "Budget $"},
    {"type": "budget_percentage", "range": "current_period", "year": "current", "name": "Budget %"},
    {"type": "budget_variance", "range": "current_period", "name": "Budget Var"},
    {"type": "actual", "range": "current_period", "year": "prior", "name": "PTD LY $"},
    {"type": "percentage", "range": "current_period", "year": "prior", "name": "PTD LY %"},
    {"type": "actual", "range": "ytd", "year": "current", "name": "YTD $"},
    {"type": "percentage", "range": "ytd", "year": "current", "name": "YTD %"},
    {"type": "budget_actual", "range": "ytd", "year": "current", "name": "Budget $"},
    {"type": "budget_percentage", "range": "ytd", "year": "current", "name": "Budget %"},
    {"type": "budget_variance", "range": "ytd", "name": "Budget Var"},
    {"type": "actual", "range": "ytd", "year": "prior", "name": "YTD LY $"},
    {"type": "percentage", "range": "ytd", "year": "prior", "name": "YTD LY %"}
  ],
  "missing_transactions_calculation_disabled": false,
  "view_by_options": ["rooms_sold"],
  "items": [
    {
      "id": "summary",
      "name": "Summary",
      "_description": "This section consists of items that use standard hotel metrics to calculate the values"
    },
    {
      "id": "rooms_available",
      "name": "Rooms Available to sell",
      "parent_id": "summary",
      "type": {
        "name": "reference",
        "reference": "owners_operating_statement/rooms_available",
        "metric": {
          "name": "Available Rooms"
        }
      }
    },
    {
      "id": "rooms_sold",
      "name": "Rooms Sold",
      "parent_id": "summary",
      "type": {
        "name": "reference",
        "reference": "owners_operating_statement/rooms_sold",
        "metric": {
          "name": "Sold Rooms"
        }
      }
    },
    {
      "id": "occupancy_percent",
      "name": "Occupancy %",
      "parent_id": "summary",
      "type": {
        "name": "reference",
        "reference": "owners_operating_statement/occupancy_percent"
      },
      "values": {
        "actual": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "rooms_sold"
              },
              "arg2": {
                "item_id": "rooms_available"
              }
            }
          }
        }
      }
    },
    {
      "id": "management_fee",
      "name": "Management Fee"
    },
    {
      "id": "base_fee",
      "name": "Base Fee",
      "parent_id": "management_fee",
      "type": {
        "name": "quickbooks_ledger"
      },
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "base_fee"
              },
              "arg2": {
                "item_id": "owners_operating_statement/total_operating_revenue"
              }
            }
          }
        }
      }
    },
    {
      "id": "incentive_fees",
      "name": "Incentive Fees",
      "parent_id": "management_fee",
      "type": {
        "name": "quickbooks_ledger"
      },
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "incentive_fees"
              },
              "arg2": {
                "item_id": "owners_operating_statement/total_operating_revenue"
              }
            }
          }
        }
      }
    },
    {
      "id": "total_management_fee",
      "name": "Total Management Fee",
      "parent_id": "management_fee",
      "totals": true,
      "values": {
        "percentage": {
          "value": {
            "expression": {
              "operator": "%",
              "arg1": {
                "item_id": "total_management_fee"
              },
              "arg2": {
                "item_id": "owners_operating_statement/total_operating_revenue"
              }
            }
          }
        }
      }
    }
  ]
}
